### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Laviesss** [vincent64/minecraft-chat-history#3]
I know you havent updated this in months but like it would be nice to have the ability to set the minecraft directory for this since my directory isnt in appdata folder

**Comment by vincent64** [comment]
Hey!
You already can specify the path to your log files directory, by clicking on the "Settings" button in the bottom right corner of the window, and change the path in the Settings window. Here's a couple of screenshots :

![mcch_1](https://github.com/user-attachments/assets/e7a640c9-6ab3-4c38-8f0e-705373a3c40b)
![image](https://github.com/user-attachments/assets/f8d19109-8f75-4670-8c79-67baede86e6d)

Let me know if that helps you.

**Comment by Laviesss** [comment]
oh alright thank you
